
USE ASEAuthDb;
GO

IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL DROP TABLE dbo.Users;
GO

CREATE TABLE dbo.Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FullName NVARCHAR(200) NOT NULL,
  Email NVARCHAR(200) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(MAX) NOT NULL,
  PhoneNumber NVARCHAR(50) NULL,
  DateOfBirth DATE NULL,
  Role NVARCHAR(50) NOT NULL CONSTRAINT DF_Users_Role DEFAULT ('User'),
  IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
  CreatedAt DATETIME NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT (GETDATE()),
  UpdatedAt DATETIME NULL
);
GO


IF OBJECT_ID('dbo.AuditLogs', 'U') IS NOT NULL DROP TABLE dbo.AuditLogs;
GO

CREATE TABLE dbo.AuditLogs (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NULL,
  Action NVARCHAR(100) NOT NULL,
  CreatedAt DATETIME NOT NULL CONSTRAINT DF_AuditLogs_CreatedAt DEFAULT (GETDATE()),
  Details NVARCHAR(1000) NULL
);
GO
